/**
 * Embedded scanner filter-spec catalog — the input vocabulary for building a
 * scan (create_scan / update_scan_filters, both Phase 4).
 *
 * WHY EMBEDDED (not fetched): the official Robinhood Trading MCP's
 * get_scanner_filter_specs is served by the gRPC-transcoded Beacon Scanner
 * service. Its filter-spec REST route is not reachable with a web-session Bearer
 * token, and the raw beacon wire model (a bundled `supportedInputs` object,
 * camelCase) is structurally different from the flat, snake_case DTO the
 * official tool emits (value_type / unit_type / supported_lengths /
 * supported_intervals / supported_plots). Reshaping raw -> that DTO across every
 * value/unit/length/interval/plot variant would be an UNVERIFIABLE transform.
 * So this catalog is the official tool's *output*, captured verbatim — the same
 * account-agnostic data every caller receives — not a reverse-engineered read.
 *
 * PROVENANCE: captured directly from the official Robinhood Trading MCP
 * (get_scanner_filter_specs) on 2026-07-14; 56 specs. Verified byte-for-byte
 * against a second live capture at author time. This is a STATIC catalog, not a
 * live REST read — Robinhood may add or remove filters over time. To refresh:
 * re-call the official tool, diff, and regenerate. See the scanner drift-guard
 * unit test (__tests__/client/scanner-filter-specs.test.ts).
 *
 * GENERATED — do not hand-edit individual entries; regenerate from a fresh
 * official capture to keep the catalog authoritative.
 */

import type { ScannerFilterSpec } from "./types.js";

/** ISO date (YYYY-MM-DD) this catalog was captured from the official MCP. */
export const SCANNER_FILTER_SPECS_CAPTURED_AT = "2026-07-14";

/**
 * The 56 account-agnostic scanner filter specs, exactly as the official
 * get_scanner_filter_specs tool returns them (its `data.filter_specs`).
 */
export const SCANNER_FILTER_SPECS: readonly ScannerFilterSpec[] = [
  {
    filter_type: "FILTER_TYPE_INSTRUMENT_TYPE",
    display_name: "Asset type",
    filter_group: "FUNDAMENTAL",
    value_type: "STRING",
    unit_type: "PLAIN",
    supported_predicates: ["=", "ANY_OF"],
  },
  {
    filter_type: "FILTER_TYPE_EPS",
    display_name: "EPS",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_EARNINGS_DATE",
    display_name: "Earnings date",
    filter_group: "FUNDAMENTAL",
    value_type: "DATETIME",
    unit_type: "PLAIN",
    supported_predicates: ["=", "!=", "BETWEEN", ">", ">=", "<=", "<"],
  },
  {
    filter_type: "FILTER_TYPE_EX_DIVIDEND_DATE",
    display_name: "Ex-dividend date",
    filter_group: "FUNDAMENTAL",
    value_type: "DATETIME",
    unit_type: "PLAIN",
    supported_predicates: ["=", "!=", "BETWEEN", ">", ">=", "<=", "<"],
  },
  {
    filter_type: "FILTER_TYPE_SHARES_FLOAT",
    display_name: "Float",
    filter_group: "FUNDAMENTAL",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_FORWARD_PE",
    display_name: "Forward P/E",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_GROSS_MARGIN",
    display_name: "Gross margin",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_MARKET_CAP",
    display_name: "Market cap",
    filter_group: "FUNDAMENTAL",
    value_type: "INTEGER",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_NET_PROFIT_MARGIN",
    display_name: "Net profit margin",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_OPERATING_MARGIN",
    display_name: "Operating margin",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_PE",
    display_name: "P/E",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_PEG",
    display_name: "PEG",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_RETURN_ON_ASSETS",
    display_name: "Return on assets",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_RETURN_ON_EQUITY",
    display_name: "Return on equity",
    filter_group: "FUNDAMENTAL",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_SECTOR",
    display_name: "Sector",
    filter_group: "FUNDAMENTAL",
    value_type: "STRING",
    unit_type: "PLAIN",
    supported_predicates: ["=", "ANY_OF"],
  },
  {
    filter_type: "FILTER_TYPE_SHARES_OUTSTANDING",
    display_name: "Shares outstanding",
    filter_group: "FUNDAMENTAL",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_CALL_VOLUME",
    display_name: "Average call volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_OPTIONS_VOLUME",
    display_name: "Average options volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_PUT_VOLUME",
    display_name: "Average put volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_HISTORICAL_VOLATILITY",
    display_name: "Historical volatility",
    filter_group: "OPTION",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_IMPLIED_VOLATILITY",
    display_name: "Implied volatility",
    filter_group: "OPTION",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_OPEN_INTEREST",
    display_name: "Open interest",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_OPEN_INTEREST_VOLUME",
    display_name: "Open interest/volume",
    filter_group: "OPTION",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_OPTIONS_VOLUME",
    display_name: "Options volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_RELATIVE_OPTIONS_VOLUME",
    display_name: "Relative options volume",
    filter_group: "OPTION",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_CALL_OPEN_INTEREST",
    display_name: "Total call open interest",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_CALL_VOLUME",
    display_name: "Total call volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_PUT_OPEN_INTEREST",
    display_name: "Total put open interest",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_TOTAL_PUT_VOLUME",
    display_name: "Total put volume",
    filter_group: "OPTION",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_PERCENT_CHANGE_FROM_CLOSE",
    display_name: "% Change",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<=", "<", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
    supported_plots: ["High", "Low", "Open", "Close"],
  },
  {
    filter_type: "FILTER_TYPE_ASK_PRICE",
    display_name: "Ask Price",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", "<", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_VOLUME",
    display_name: "Average volume",
    filter_group: "PRICE_VOLUME",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_BID_PRICE",
    display_name: "Bid Price",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", "<", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_CLOSE",
    display_name: "Close",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_GAP",
    display_name: "Gap",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "PERCENTAGE",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_HIGH",
    display_name: "High",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 3, 4, 5, 6, 15, 30, 52],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_LAST",
    display_name: "Last",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_LOW",
    display_name: "Low",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 3, 4, 5, 6, 15, 30, 52],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_DOLLAR_CHANGE_FROM_CLOSE",
    display_name: "Net change",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
    supported_plots: ["High", "Open", "Close", "Low"],
  },
  {
    filter_type: "FILTER_TYPE_OPEN",
    display_name: "Open",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "DOLLAR",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
  },
  {
    filter_type: "FILTER_TYPE_RELATIVE_VOLUME",
    display_name: "Relative volume",
    filter_group: "PRICE_VOLUME",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [1, 2, 4, 5, 10, 14, 15, 30, 60, 90],
    supported_intervals: ["1m", "1h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_VOLUME",
    display_name: "Volume",
    filter_group: "PRICE_VOLUME",
    value_type: "INTEGER",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_AROON_INDICATOR",
    display_name: "Aroon Indicator",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
    supported_plots: ["Up", "Down"],
  },
  {
    filter_type: "FILTER_TYPE_AROON_OSCILLATOR",
    display_name: "Aroon Oscillator",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_DIRECTIONAL_INDEX",
    display_name: "Average directional index",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [9, 10, 14, 20, 25, 50, 100],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_AVERAGE_TRUE_RANGE",
    display_name: "Average true range",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [10, 14, 20, 25],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_BOLLINGER_BAND",
    display_name: "Bollinger band",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
    supported_plots: ["Up", "Down"],
  },
  {
    filter_type: "FILTER_TYPE_COMMODITY_CHANNEL_INDEX",
    display_name: "CCI",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [10, 14, 20, 25],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_EMA",
    display_name: "EMA",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [
      2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 20, 21, 25, 26, 30, 34, 40, 50, 55, 60, 75, 89, 100,
      120, 144, 150, 200,
    ],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_MACD",
    display_name: "MACD",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_RSI",
    display_name: "RSI",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [2, 3, 4, 5, 7, 9, 10, 14, 20, 21, 25, 30],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_RESISTANCE",
    display_name: "Resistance",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<="],
    supported_intervals: ["1d", "1w", "1m"],
    supported_plots: ["resistance1", "resistance2"],
  },
  {
    filter_type: "FILTER_TYPE_STOCHASTIC_OSCILLATOR",
    display_name: "Stochastic oscillator",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
    supported_plots: ["fast", "slow"],
  },
  {
    filter_type: "FILTER_TYPE_SUPPORT",
    display_name: "Support",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<="],
    supported_intervals: ["1d", "1w", "1m"],
    supported_plots: ["support1", "support2"],
  },
  {
    filter_type: "FILTER_TYPE_VWAP",
    display_name: "VWAP",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
  {
    filter_type: "FILTER_TYPE_WILLIAMS_PERCENT_RANGE",
    display_name: "Williams Percent Range",
    filter_group: "TECHNICAL",
    value_type: "DECIMAL",
    unit_type: "PLAIN",
    supported_predicates: [">", ">=", "<", "<=", "BETWEEN", "OUTSIDE"],
    supported_lengths: [10, 14, 20, 25],
    supported_intervals: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"],
  },
];
